// per-scene codegen barrel.
//
// reads the captured `module.scenes` (declared via `scene('<id>')` in user
// code) and emits `src/generated/scenes.ts`. the barrel static-imports each
// scene's `.scene.json` and calls `__kit.registerScene` at module-eval.
// each call stashes the payload into an engine-side map. `EngineClient.load`
// / `EngineServer.load` walk that map after `Project.load` and apply each
// payload via `populateScene`.
//
// edit mode additionally walks `content/scenes/blueprints/**` and registers
// every blueprint `.scene.json` found. blueprints are editor-authored — no
// user code calls `scene('blueprints/foo')` — so the FS walk is the only
// path that gets them into the registry where the icon renderer can find
// them. the editor's scenes-tab listing is fed separately by
// `bongle:scene-list` (kit/vite/plugin.ts), which walks the full
// `content/scenes/` tree, so undeclared author scenes still surface there
// without needing a SceneHandle. play mode keeps the strict "declared only"
// surface so prod bundles don't grow with editor-only artifacts.
//
// vite handles the JSON imports natively — in dev the json is fetched off
// the file system; in prod `vite build` inlines it into the bundle. one
// path covers both. per-chunk binary payloads inside the json are gzip-base64
// strings that stay inert until `loadVoxels` decodes them at runtime.

import fs from 'node:fs';
import path from 'node:path';
import type { ModuleVersion } from 'bongle/internal';
import { writeFileIfChanged } from './util';

const SCENES_SUBDIR = path.join('content', 'scenes');
const SCENE_EXT = '.scene.json';

const EMPTY_BARREL = `// auto-generated by asset pipeline — do not edit
export {};
`;

export type BuildScenesOptions = {
    /** absolute path to the project root. */
    projectDir: string;
    /** kit invocation mode. `edit` additionally walks
     *  `content/scenes/blueprints/**` so editor-authored blueprints get a
     *  SceneHandle (used by the icon renderer + prefab placement). `play`
     *  registers only ids declared via `scene('id')`. */
    mode: 'edit' | 'play';
};

function walkSceneFiles(dir: string, prefix: string, out: string[]): void {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, ent.name);
        if (ent.isDirectory()) {
            walkSceneFiles(full, prefix ? `${prefix}/${ent.name}` : ent.name, out);
        } else if (ent.isFile() && ent.name.endsWith(SCENE_EXT)) {
            const stem = ent.name.slice(0, -SCENE_EXT.length);
            out.push(prefix ? `${prefix}/${stem}` : stem);
        }
    }
}

export async function buildScenes(module: ModuleVersion, opts: BuildScenesOptions): Promise<void> {
    const barrelPath = path.join(opts.projectDir, 'src', 'generated', 'scenes.ts');
    fs.mkdirSync(path.dirname(barrelPath), { recursive: true });

    const scenesDir = path.join(opts.projectDir, SCENES_SUBDIR);
    const barrelDir = path.dirname(barrelPath);

    // union of declared ids + (edit mode) filesystem-discovered blueprints.
    // Set preserves dedup; sort for stable barrel output. the walk is scoped
    // to `blueprints/` so an undeclared `content/scenes/foo.scene.json`
    // doesn't get auto-registered with a SceneHandle — the runtime only
    // sees scenes the user actually declared via `scene()`, plus blueprints.
    const ids = new Set<string>(module.scenes.keys());
    if (opts.mode === 'edit') {
        const blueprintsDir = path.join(scenesDir, 'blueprints');
        if (fs.existsSync(blueprintsDir)) {
            const found: string[] = [];
            walkSceneFiles(blueprintsDir, 'blueprints', found);
            for (const id of found) ids.add(id);
        }
    }
    const sortedIds = Array.from(ids).sort();

    type Entry = { id: string; sceneRel: string };
    const entries: Entry[] = [];

    for (const id of sortedIds) {
        const sceneAbs = path.join(scenesDir, id + SCENE_EXT);
        if (!fs.existsSync(sceneAbs)) {
            // declaration exists but file doesn't — warn and skip. handle
            // stays empty; prefabs depending on it won't instantiate.
            console.warn(
                `[bongle] declared scene "${id}" not found on disk — handle stays empty, prefabs depending on it won't instantiate`,
            );
            continue;
        }
        entries.push({ id, sceneRel: toImport(barrelDir, sceneAbs) });
    }

    if (entries.length === 0) {
        writeFileIfChanged(barrelPath, EMPTY_BARREL);
        return;
    }

    const lines: string[] = [];
    lines.push(`// auto-generated by asset pipeline — do not edit`);
    lines.push(``);
    // `__kit` is provided in module scope by the kit Vite plugin's
    // prelude (see kit/src/vite/plugin.ts) — re-importing it here would
    // collide with the prelude's top-level `import { __kit }` and parse
    // as "Identifier '__kit' has already been declared".
    for (let i = 0; i < entries.length; i++) {
        lines.push(`import _scene_${i} from '${entries[i]!.sceneRel}';`);
    }
    lines.push(``);
    for (let i = 0; i < entries.length; i++) {
        const e = entries[i]!;
        lines.push(
            `__kit.registerScene(${JSON.stringify(e.id)}, { nodes: _scene_${i}.nodes, voxels: _scene_${i}.chunks ? { chunks: _scene_${i}.chunks } : null });`,
        );
    }
    lines.push(``);
    lines.push(`export {};`);
    lines.push(``);

    writeFileIfChanged(barrelPath, lines.join('\n'));
}

function toImport(fromDir: string, absPath: string): string {
    const rel = path.relative(fromDir, absPath).split(path.sep).join('/');
    return rel.startsWith('.') ? rel : './' + rel;
}
