packages:
  - engine
  - interface
  - examples/*
  - docs/template

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@bongle/*'
  - vite

onlyBuiltDependencies:
  - '@ffmpeg-installer/*'
  - '@ffprobe-installer/*'
  - canvas
  - esbuild
  - puppeteer
  - sharp
  - skia-canvas
