import fs from 'node:fs';
import path from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import { build as viteBuild } from 'vite';
import { excludeEditorIcons } from './asset-pipeline/icons-write';
import { createPipelineState, type PipelineInternal, runAssetPipelinePass } from './asset-pipeline/pipeline';
import { resolveEngineRoot } from './asset-pipeline/run';
import { captureImportPlugin } from './capture-import-plugin';
import { envPlugin } from './env-plugin';
import { checkContent } from './migrations';
import { ensureGeneratedStubs, resetGeneratedBarrels } from './user-entry';

// Static build = single HTML+JS bundle the browser can serve as-is from
// any static host (CDN, http-server, website public dir). Same asset
// pipeline as `build` (atlas, models, scenes), but the bundler runs in
// Vite app mode with an index.html entry instead of lib mode. No
// server, no /game WS, no matchmaking — the bootstrap calls
// `EngineClient.startStandaloneRoom` and drives the frame loop directly.
//
// Used by apps/avatars (and any future "engine page" that wants block
// textures, sky, clouds, particles, etc. without spinning up a game server).

function writeBootstrap(bongleDir: string, sceneId: string): { entryHtml: string; entryTs: string } {
    const entryTs = path.join(bongleDir, 'static.ts');
    fs.writeFileSync(
        entryTs,
        `// AUTO-GENERATED by @bongle/kit static build. Do not edit by hand.
import { env } from 'bongle'
import '../src/generated'
import '../src/index'
import { EngineClient, browserResourceLoader } from 'bongle/engine-client'

env.client = true
env.server = false
env.editor = false

const state = EngineClient.init({
    mode: 'play',
    driver: {
        matchmake() {},
        platform: { commercialBreak: async () => {}, rewardedBreak: async () => false },
    },
    resourceLoader: browserResourceLoader,
})
// Mount the play-mode UI shell before load() — the React Viewport
// component owns the canvas, and the resize callback in load() needs
// viewportElement to be set before it can size the renderer.
EngineClient.mountPlayUI(state.domElement)
await EngineClient.load(state)
EngineClient.startStandaloneRoom(state, ${JSON.stringify(sceneId)})

let last = performance.now()
function loop(now: number) {
    const dt = (now - last) / 1000
    last = now
    EngineClient.update(state, dt)
    requestAnimationFrame(loop)
}
requestAnimationFrame(loop)
`,
    );

    const entryHtml = path.join(bongleDir, 'static.html');
    fs.writeFileSync(
        entryHtml,
        `<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>bongle</title>
    <style>
        body { margin: 0; padding: 0; overflow: hidden; }
        canvas { width: 100vw; height: 100vh; }
    </style>
</head>
<body>
    <script type="module" src="./static.ts"></script>
</body>
</html>
`,
    );

    return { entryHtml, entryTs };
}

async function runAssetPipelineInProcess(opts: {
    projectDir: string;
    bongleDir: string;
    engineRoot: string;
}): Promise<void> {
    await import(/* @vite-ignore */ path.join(opts.engineRoot, 'src/core/physics/physics.ts'));
    await import(/* @vite-ignore */ path.join(opts.projectDir, 'src', 'generated', 'index.ts'));
    await import(/* @vite-ignore */ path.join(opts.projectDir, 'src', 'index.ts'));
    const internal = (await import('bongle/internal')) as unknown as PipelineInternal;
    await runAssetPipelinePass(internal, { projectDir: opts.projectDir, mode: 'play', cache: false }, createPipelineState());
}

export async function buildStatic(projectDir: string, opts?: { sceneId?: string }) {
    // Production semantics for the build (see build.ts): the CLI bootstraps through a
    // Vite SSR dev server that sets NODE_ENV='development', and Vite derives
    // `isProduction` solely from NODE_ENV — so without this the static bundle ships
    // dev-only transforms (e.g. the dev JSX runtime → `jsxDEV is not a function`).
    process.env.NODE_ENV = 'production';

    const resolvedProjectDir = path.resolve(projectDir);
    if (!fs.existsSync(resolvedProjectDir)) {
        console.error(`Project directory does not exist: ${resolvedProjectDir}`);
        process.exit(1);
    }

    const sceneId = opts?.sceneId ?? 'main';
    const bongleDir = path.join(resolvedProjectDir, '.bongle');
    fs.mkdirSync(bongleDir, { recursive: true });

    const behind = checkContent(resolvedProjectDir);
    if (behind.length > 0) {
        console.error(`[bongle] content out of date (${behind.length} file(s)):`);
        for (const m of behind) {
            console.error(`  ${path.relative(resolvedProjectDir, m.file)}: v${m.from} → v${m.to}`);
        }
        console.error('run `bongle migrate` to update.');
        process.exit(1);
    }

    console.log(`[bongle] building static ${resolvedProjectDir}`);
    const start = performance.now();

    const engineRoot = resolveEngineRoot(resolvedProjectDir);
    ensureGeneratedStubs(resolvedProjectDir);
    resetGeneratedBarrels(resolvedProjectDir);

    console.log('[bongle] running asset pipeline...');
    await runAssetPipelineInProcess({
        projectDir: resolvedProjectDir,
        bongleDir,
        engineRoot,
    });

    const { entryHtml } = writeBootstrap(bongleDir, sceneId);

    const outDir = path.join(resolvedProjectDir, 'dist', 'static');
    console.log('[bongle] bundling static SPA...');
    await viteBuild({
        root: bongleDir,
        // Relative asset paths so the bundle works at any mount point —
        // root http-server, iframed under `/avatars/`, CDN subpath, etc.
        base: './',
        plugins: [
            tailwindcss(),
            envPlugin({ client: true, server: false, editor: false, offline: false }),
            captureImportPlugin(resolvedProjectDir),
        ],
        define: {
            'process.env.NODE_ENV': JSON.stringify('production'),
        },
        build: {
            outDir,
            emptyOutDir: true,
            rollupOptions: {
                input: entryHtml,
                output: {
                    // Entry JS sits at the root next to copied resources so the
                    // engine's `import.meta.url`-relative asset resolution lands
                    // on voxels-atlas.json etc. Code-split chunks stay nested.
                    entryFileNames: '[name]-[hash].js',
                    chunkFileNames: 'assets/[name]-[hash].js',
                    assetFileNames: (asset) =>
                        asset.names?.some((n) => n.endsWith('.css')) ? 'index.css' : 'assets/[name]-[hash][extname]',
                },
            },
        },
        resolve: { preserveSymlinks: false },
        logLevel: 'warn',
    });

    // Rename .bongle/static.html → dist/static/index.html so the bundle
    // is servable from the root path.
    const emittedHtml = path.join(outDir, 'static.html');
    const indexHtml = path.join(outDir, 'index.html');
    if (fs.existsSync(emittedHtml)) {
        fs.renameSync(emittedHtml, indexHtml);
    }

    // Copy resources/client/* into dist/static/ — voxel + sprite atlases
    // and other browser-side runtime assets the engine fetches via assetUrl().
    const projectResourcesClientDir = path.join(resolvedProjectDir, 'resources', 'client');
    if (fs.existsSync(projectResourcesClientDir)) {
        // exclude editor-only per-id icon dirs (scenes/, prefabs/); keep the
        // block-icon atlas + all real runtime assets.
        fs.cpSync(projectResourcesClientDir, outDir, {
            recursive: true,
            filter: excludeEditorIcons(projectResourcesClientDir),
        });
    }

    const elapsed = (performance.now() - start).toFixed(0);
    console.log(`[bongle] static build complete in ${elapsed}ms`);
    console.log(`[bongle]   dist/static/index.html`);
}
