import fs from 'node:fs';
import path from 'node:path';

const EMPTY_BARREL = `// auto-generated by asset pipeline — do not edit
export {};
`;

/**
 * list of generated/* sub-barrels imported by `generated/index.ts`. add
 * a new entry here when a new codegen category comes online (scenes,
 * prefabs, etc) — that's the single edit point. each entry gets:
 *   - a cold-start stub (empty barrel) if the file is missing
 *   - a side-effect import line in the generated/index.ts barrel
 */
const GENERATED_BARRELS = ['models', 'scenes', 'sounds'] as const;

/**
 * ensure `src/generated/` is in a buildable state:
 *   - cold-start stubs exist for every sub-barrel (asset pipeline will
 *     overwrite them with real content)
 *   - `src/generated/index.ts` exists and re-imports every sub-barrel
 *
 * `index.ts` is always (re)written so the list stays consistent with
 * GENERATED_BARRELS — drift-proof.
 */
export function ensureGeneratedStubs(projectDir: string): void {
    const generatedDir = path.join(projectDir, 'src', 'generated');
    fs.mkdirSync(generatedDir, { recursive: true });

    for (const name of GENERATED_BARRELS) {
        const barrelPath = path.join(generatedDir, `${name}.ts`);
        if (!fs.existsSync(barrelPath)) fs.writeFileSync(barrelPath, EMPTY_BARREL);
    }

    const indexLines = ['// auto-generated, do not edit', ''];
    for (const name of GENERATED_BARRELS) indexLines.push(`import './${name}';`);
    indexLines.push('', 'export {};', '');
    fs.writeFileSync(path.join(generatedDir, 'index.ts'), indexLines.join('\n'));
}

/**
 * cold-start reset of sub-barrel content. Called once at dev/build
 * entry, BEFORE the first user-script build, so a stale sub-barrel
 * left by a previous run can't poison the user-script bundle.
 *
 * Why this is needed: sub-barrels are owned by the asset pipeline,
 * but the user-script bundler statically imports them via
 * `generated/index.ts`. If the kit's barrel template changes (e.g.
 * a renamed internal export), the previous run's barrel is broken —
 * the user-script bundle fails — the asset pipeline can't re-emit
 * because it imports that bundle to discover defs (chicken-and-egg).
 * Resetting to empty stubs here breaks the cycle: bundle succeeds
 * with no model registrations, pipeline runs, sub-barrels regenerate
 * with current schema, next rebuild picks them up.
 *
 * Don't call this from runBuild — that fires on every src change and
 * would clobber the real barrel between rebuilds.
 */
export function resetGeneratedBarrels(projectDir: string): void {
    const generatedDir = path.join(projectDir, 'src', 'generated');
    fs.mkdirSync(generatedDir, { recursive: true });
    for (const name of GENERATED_BARRELS) {
        fs.writeFileSync(path.join(generatedDir, `${name}.ts`), EMPTY_BARREL);
    }
}

