// Content-hash the assembled Blockbench bundle and place it under a hashed
// directory. Blockbench is upstream's app: its index.html + bundle load every
// asset by stable, unhashed names (css/*, dist/bundle.js, lib/gif.worker.js,
// lang/en.json…), so the bundle can't be cache-busted per-file. Instead we
// version the WHOLE tree by one content hash and serve it at
//   static/blockbench/<hash>/…
// The editor embeds that hash in the iframe URL (see ui/blockbench-version.ts),
// so a changed bundle lands at a new path and the whole thing is safe to cache
// `immutable`. Identical rebuilds hash the same → the path (and caches) survive.
//
// Usage: node stamp.mjs <srcDir> <baseDir> <versionModule>
//   srcDir        the freshly-assembled bundle (e.g. <baseDir>/.staging)
//   baseDir       static/blockbench — ends up holding exactly one <hash>/ dir
//   versionModule editor TS module the hash is written to
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';

const [srcDir, baseDir, versionModule] = process.argv.slice(2);
if (!srcDir || !baseDir || !versionModule) {
	console.error('usage: node stamp.mjs <srcDir> <baseDir> <versionModule>');
	process.exit(1);
}

// Deterministic hash over every file's relative path + bytes, path-sorted so the
// result depends only on content, not on readdir order.
function hashTree(dir) {
	const files = [];
	(function walk(d) {
		for (const name of readdirSync(d).sort()) {
			const p = join(d, name);
			if (statSync(p).isDirectory()) walk(p);
			else files.push(p);
		}
	})(dir);
	files.sort();
	const h = createHash('sha256');
	for (const f of files) {
		h.update(relative(dir, f).split(sep).join('/'));
		h.update('\0');
		h.update(readFileSync(f));
		h.update('\0');
	}
	return h.digest('hex').slice(0, 16);
}

const hash = hashTree(srcDir);
const target = join(baseDir, hash);

if (resolve(srcDir) !== resolve(target)) {
	rmSync(target, { recursive: true, force: true });
	renameSync(srcDir, target);
}

// Keep exactly one bundle dir: drop old hashes and any leftover staging.
for (const name of readdirSync(baseDir)) {
	if (name !== hash) rmSync(join(baseDir, name), { recursive: true, force: true });
}

writeFileSync(
	versionModule,
	`// Generated by lib/blockbench/scripts/stamp.mjs — do not edit by hand.\n` +
		`// Content hash of the assembled Blockbench bundle. The editor embeds it in\n` +
		`// the iframe URL (static/blockbench/<hash>/) so the internally-unhashed\n` +
		`// bundle can be served immutable; a changed bundle rotates the hash.\n` +
		`export const BLOCKBENCH_VERSION = '${hash}';\n`,
);

console.log(`==> Stamped Blockbench bundle: ${hash}`);
