export type {
    CanvasTouch,
    Cursor,
    Input,
    JoystickState,
    MouseButton,
    MouseKeyboardInput,
    TouchButtonState,
    TouchInput,
} from '../client/input';
export {
    consumeTouchButtonLookDrag,
    getCanvasTouch,
    getCanvasTouches,
    getCanvasTouchesJustEnded,
    getCursor,
    getJoystick,
    getPinchDelta,
    getPinchScale,
    isJoystickJustActive,
    isJoystickJustReleased,
    isKeyDown,
    isKeyJustDown,
    isKeyJustUp,
    isMouseDown,
    isMouseDragStart,
    isMouseJustDown,
    isMouseJustLocked,
    isMouseJustUp,
    isMouseLocked,
    isMouseTap,
    isPointerCapturedByUi,
    isTouchButtonDown,
    isTouchButtonJustDown,
    isTouchButtonJustUp,
    wasMouseLocked,
} from '../client/input';
