import type { Filesystem } from '../../../os/interface';
import type { RegistryStore as KindStore } from '../../core/registry';
import type { ResourceLoader } from '../../core/resource-loader';
import type { SoundDef } from '../../core/sounds/sounds';
import { BAKE_CONCURRENCY, mapConcurrent } from './concurrency';
import type { DecodeAudio } from './decode-audio';
import { encodeMp3 } from './mp3';
import { encodeOpusAtlasWebm } from './opus';

const SAMPLE_RATE = 48000;
const STANDALONE_BITRATE_KBPS = 128;
/** VBR; mono SFX is near-transparent at this bitrate, and the atlas ships to every player, so size wins. */
const ATLAS_OPUS_BITRATE = 48_000;
/** libopus's default 10 is byte-identical at this bitrate but twice as slow to encode. */
const ATLAS_OPUS_COMPLEXITY = 5;

// folded into atlasHash so a builder-format change invalidates any on-disk atlas + manifest
// without requiring a cache wipe; bump when the encode pipeline affects offsets or byte layout.
const ATLAS_FORMAT_VERSION = 'v9-opus-webm-48k';

export type BuildAudioOptions = {
    /** the editor project filesystem the atlas/standalone/manifest/barrel
     *  write into (host-provided; see pipeline InitCtx). */
    fs: Filesystem;
    /** bake-input byte loader: registry `src` refs (URLs / project-relative
     *  paths) → bytes. host-provided (see pipeline InitCtx). */
    loader: ResourceLoader;
    /** host-injected audio decode (browser OfflineAudioContext). See
     *  bake/decode-audio.ts and the pipeline InitCtx. */
    decodeAudio: DecodeAudio;
};

export type AudioManifestAtlasEntry = {
    id: string;
    /** seconds, feeds AudioBufferSourceNode.start(when, offset, duration). */
    offset: number;
    duration: number;
};

export type AudioManifestStandaloneEntry = {
    id: string;
    /** url relative to the resources/client serve root (e.g. "audio/theme.mp3"). */
    url: string;
    durationSec: number;
};

export type AudioManifest = {
    /** combined hash over both buckets, drives the artifact cache check. */
    hash: string;
    /** hash over only the atlas bucket sources, for selective rebuild. */
    atlasHash: string;
    /** hash over only the standalone bucket sources, for selective rebuild. */
    standaloneHash: string;
    sampleRate: number;
    atlas: AudioManifestAtlasEntry[];
    standalone: AudioManifestStandaloneEntry[];
};

/** Per-id codegen entry, input to the barrel emitter. */
export type CodegenEntry = {
    id: string;
    /** the declared display name and search tags, carried through so a barrel
     *  re-registration keeps what the author wrote rather than the id. */
    name: string;
    tags: readonly string[];
    src: string;
    long: boolean;
    duration: number;
};

/** A declared sound with its source bytes resolved through the loader. */
type LoadedSource = {
    id: string;
    src: string;
    long: boolean;
    bytes: Uint8Array;
};

// project-relative outputs on the ctx Filesystem.
const CLIENT_DIR = 'resources/client';
const ATLAS_PATH = `${CLIENT_DIR}/audio-atlas.webm`;
const STANDALONE_DIR = `${CLIENT_DIR}/audio`;
const MANIFEST_PATH = `${CLIENT_DIR}/audio-manifest.json`;
const BARREL_PATH = 'src/generated/sounds.ts';

const enc = new TextEncoder();

const EMPTY_BARREL = `// auto-generated by asset pipeline — do not edit
export {};
`;

/**
 * duration (from the decoded PCM sample count) is baked into each handle literal in the barrel
 * so user code reads `handle.duration` statically. returns true if anything was rebuilt.
 */
export async function buildAudio(soundsRegistry: KindStore<SoundDef>, opts: BuildAudioOptions): Promise<boolean> {
    const { fs, loader, decodeAudio } = opts;

    // sorted by id for deterministic order; the atlas concatenation order (and thus its offsets) follows this.
    const all = [...soundsRegistry.byId.entries()]
        .map(([id, h]) => ({ id, name: h.name, tags: h.tags, src: h.src, long: h.long }))
        .sort((a, b) => a.id.localeCompare(b.id));

    if (all.length === 0) {
        // emit a valid empty manifest rather than deleting it, so the client never 404s. the
        // empty `hash` reads back falsy, so change gates treat it like missing audio.
        await fs.remove(ATLAS_PATH);
        await fs.remove(STANDALONE_DIR, { recursive: true });
        const empty: AudioManifest = {
            hash: '',
            atlasHash: '',
            standaloneHash: '',
            sampleRate: SAMPLE_RATE,
            atlas: [],
            standalone: [],
        };
        await fs.write(MANIFEST_PATH, JSON.stringify(empty, null, 2));
        await fs.writeIfChanged(BARREL_PATH, EMPTY_BARREL);
        return false;
    }

    // Resolve source bytes once, up front: they feed the content hash gate
    // (and, on rebuild, the decoder). A missing source is fatal (a declared
    // sound with no file can't be baked).
    const tLoad = performance.now();
    const atlasSources = await loadSources(
        loader,
        all.filter((s) => !s.long),
    );
    const standaloneSources = await loadSources(
        loader,
        all.filter((s) => s.long),
    );
    console.log(`[bongle] audio sources: ${all.length} files loaded in ${(performance.now() - tLoad).toFixed(0)}ms`);

    const atlasHash = await computeBucketHash(atlasSources, ATLAS_FORMAT_VERSION);
    const standaloneHash = await computeBucketHash(standaloneSources);
    const combinedHash = await sha256Hex(enc.encode(`${atlasHash}${standaloneHash}`));

    const existing = await readManifest(fs);
    const atlasUpToDate = existing?.atlasHash === atlasHash && (atlasSources.length === 0 || (await fs.exists(ATLAS_PATH)));
    const standaloneUpToDate =
        existing?.standaloneHash === standaloneHash &&
        (await allExist(
            fs,
            standaloneSources.map((s) => standalonePath(s.id)),
        ));

    let manifest: AudioManifest;
    let rebuilt = false;

    if (existing?.hash === combinedHash && atlasUpToDate && standaloneUpToDate) {
        // full cache hit, reuse the on-disk manifest for codegen durations.
        manifest = existing;
    } else {
        console.log(`[bongle] building audio (${atlasSources.length} atlas, ${standaloneSources.length} standalone)...`);

        const atlasEntries: AudioManifestAtlasEntry[] =
            atlasUpToDate && existing ? existing.atlas : await buildAtlas(decodeAudio, atlasSources, fs);

        let standaloneEntries: AudioManifestStandaloneEntry[];
        if (standaloneUpToDate && existing) {
            standaloneEntries = existing.standalone;
        } else {
            standaloneEntries = await buildStandalones(decodeAudio, standaloneSources, fs);
            // prune stale standalones whose id is no longer declared.
            await pruneStandalones(fs, new Set(standaloneEntries.map((e) => e.id)));
        }

        manifest = {
            hash: combinedHash,
            atlasHash,
            standaloneHash,
            sampleRate: SAMPLE_RATE,
            atlas: atlasEntries,
            standalone: standaloneEntries,
        };
        await fs.write(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
        rebuilt = true;
        console.log(`[bongle] audio built: atlas ${atlasEntries.length} clips, standalone ${standaloneEntries.length} files`);
    }

    // joins all declared sounds against the manifest's decoded durations; cheap to re-emit unconditionally.
    const durationById = new Map<string, number>();
    for (const e of manifest.atlas) durationById.set(e.id, e.duration);
    for (const e of manifest.standalone) durationById.set(e.id, e.durationSec);

    const codegenEntries: CodegenEntry[] = all.map((s) => ({
        id: s.id,
        name: s.name,
        tags: s.tags,
        src: s.src,
        long: s.long,
        duration: durationById.get(s.id) ?? 0,
    }));

    await fs.writeIfChanged(BARREL_PATH, renderBarrel(codegenEntries));

    return rebuilt;
}

async function loadSources(
    loader: ResourceLoader,
    sounds: Array<{ id: string; src: string; long: boolean }>,
): Promise<LoadedSource[]> {
    // each load is a service-worker round trip to the project fs; mapConcurrent keeps input order.
    return mapConcurrent(sounds, BAKE_CONCURRENCY, async (s) => {
        let bytes: Uint8Array;
        try {
            bytes = await loader.loadBytes(s.src);
        } catch {
            throw new Error(`[bongle] sound "${s.id}" source missing or unreadable: ${s.src}`);
        }
        return { ...s, bytes };
    });
}

async function readManifest(projectFs: Filesystem): Promise<AudioManifest | null> {
    try {
        const parsed = JSON.parse(await projectFs.readText(MANIFEST_PATH)) as Partial<AudioManifest>;
        if (
            typeof parsed.hash === 'string' &&
            typeof parsed.atlasHash === 'string' &&
            typeof parsed.standaloneHash === 'string' &&
            Array.isArray(parsed.atlas) &&
            Array.isArray(parsed.standalone)
        ) {
            return parsed as AudioManifest;
        }
    } catch {
        /* fall through */
    }
    return null;
}

/** order matters, it's the atlas concat order (id-sorted by the caller). */
async function computeBucketHash(sources: LoadedSource[], salt = ''): Promise<string> {
    const parts: string[] = [];
    if (salt) parts.push(salt);
    for (const s of sources) parts.push(s.id, s.src, await sha256Hex(s.bytes));
    return sha256Hex(enc.encode(parts.join('\0')));
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
    // cast: loader/TextEncoder Uint8Arrays are ArrayBuffer-backed in practice,
    // but their type is the wider ArrayBufferLike that BufferSource rejects.
    const digest = await crypto.subtle.digest('SHA-256', bytes as unknown as BufferSource);
    const view = new Uint8Array(digest);
    let hex = '';
    for (const b of view) hex += b.toString(16).padStart(2, '0');
    return hex;
}

/** per-channel s16 -> mono s16 (channel average); the atlas is mono. */
function downmixMono(channels: Int16Array[]): Int16Array {
    if (channels.length === 1) return channels[0]!;
    const n = channels[0]!.length;
    const out = new Int16Array(n);
    for (let i = 0; i < n; i++) {
        let sum = 0;
        for (const c of channels) sum += c[i]!;
        out[i] = Math.round(sum / channels.length);
    }
    return out;
}

async function buildAtlas(decodeAudio: DecodeAudio, sources: LoadedSource[], fs: Filesystem): Promise<AudioManifestAtlasEntry[]> {
    if (sources.length === 0) {
        await fs.remove(ATLAS_PATH);
        return [];
    }

    // decode order is load-bearing: the concatenation below is what each clip's atlas offset is
    // derived from. mapConcurrent keeps input order even though decodes fan out concurrently.
    const tDecode = performance.now();
    const pcmChunks = await mapConcurrent(sources, BAKE_CONCURRENCY, async (s) =>
        downmixMono((await decodeAudio(s.bytes, SAMPLE_RATE)).channels),
    );
    const sampleCounts = pcmChunks.map((mono) => mono.length);
    const pcm = concatInt16(pcmChunks);

    const tEncode = performance.now();
    const atlasBytes = await encodeOpusAtlasWebm(pcm, ATLAS_OPUS_BITRATE, ATLAS_OPUS_COMPLEXITY);
    const tDone = performance.now();
    console.log(
        `[bongle] audio atlas: ${sources.length} clips, ${(pcm.length / SAMPLE_RATE).toFixed(1)}s, ` +
            `decode ${(tEncode - tDecode).toFixed(0)}ms, encode ${(tDone - tEncode).toFixed(0)}ms, ${(atlasBytes.length / 1024).toFixed(0)}KB`,
    );
    await fs.write(ATLAS_PATH, atlasBytes);

    const entries: AudioManifestAtlasEntry[] = [];
    let cumSamples = 0;
    for (let i = 0; i < sources.length; i++) {
        const samples = sampleCounts[i]!;
        entries.push({
            id: sources[i]!.id,
            offset: cumSamples / SAMPLE_RATE,
            duration: samples / SAMPLE_RATE,
        });
        cumSamples += samples;
    }
    return entries;
}

async function buildStandalones(
    decodeAudio: DecodeAudio,
    sources: LoadedSource[],
    fs: Filesystem,
): Promise<AudioManifestStandaloneEntry[]> {
    // the mp3 encode is lamejs, pure JS and in-thread, so only decode and write actually overlap here.
    return mapConcurrent(sources, BAKE_CONCURRENCY, async (s) => {
        const decoded = await decodeAudio(s.bytes, SAMPLE_RATE);
        const mp3 = encodeMp3(decoded.channels, SAMPLE_RATE, STANDALONE_BITRATE_KBPS);
        await fs.write(standalonePath(s.id), mp3);
        return { id: s.id, url: `audio/${s.id}.mp3`, durationSec: decoded.channels[0]!.length / SAMPLE_RATE };
    });
}

async function pruneStandalones(fs: Filesystem, liveIds: Set<string>): Promise<void> {
    for (const [name, kind] of await fs.readDir(STANDALONE_DIR)) {
        if (kind !== 'file' || !name.endsWith('.mp3')) continue;
        const id = name.replace(/\.mp3$/, '');
        if (!liveIds.has(id)) await fs.remove(`${STANDALONE_DIR}/${name}`);
    }
}

function standalonePath(id: string): string {
    return `${STANDALONE_DIR}/${id}.mp3`;
}

async function allExist(fs: Filesystem, paths: string[]): Promise<boolean> {
    for (const p of paths) if (!(await fs.exists(p))) return false;
    return true;
}

function concatInt16(chunks: Int16Array[]): Int16Array {
    let total = 0;
    for (const c of chunks) total += c.length;
    const out = new Int16Array(total);
    let offset = 0;
    for (const c of chunks) {
        out.set(c, offset);
        offset += c.length;
    }
    return out;
}

/** @internal exported for the codegen barrel tests. */
export function renderBarrel(entries: CodegenEntry[]): string {
    if (entries.length === 0) return EMPTY_BARREL;

    assertNoIdentCollisions(entries.map((e) => e.id));

    const lines: string[] = [];
    lines.push(`// auto-generated by asset pipeline — do not edit`);
    lines.push(``);
    lines.push(`import type { SoundDef, SoundHandle } from 'bongle';`);
    lines.push(`import { registerSound } from 'bongle/internal';`);
    lines.push(``);

    for (const e of entries) {
        const constId = sanitizeIdent(e.id);
        lines.push(`// source: ${e.src}`);
        lines.push(`const ${constId}: SoundDef = {`);
        lines.push(`    soundId: ${JSON.stringify(e.id)},`);
        lines.push(`    name: ${JSON.stringify(e.name)},`);
        lines.push(`    tags: ${JSON.stringify(e.tags)},`);
        lines.push(`    src: ${JSON.stringify(e.src)},`);
        lines.push(`    long: ${e.long},`);
        lines.push(`    duration: ${fmtNum(e.duration)},`);
        lines.push(`    version: 0,`);
        lines.push(`};`);
        lines.push(``);
    }

    lines.push(`declare module 'bongle' {`);
    lines.push(`    interface SoundHandleMap {`);
    for (const e of entries) {
        lines.push(`        ${JSON.stringify(e.id)}: SoundHandle;`);
    }
    lines.push(`    }`);
    lines.push(`}`);
    lines.push(``);

    for (const e of entries) {
        lines.push(`registerSound(${JSON.stringify(e.id)}, ${sanitizeIdent(e.id)});`);
    }
    lines.push(``);
    lines.push(`export {};`);
    lines.push(``);
    return lines.join('\n');
}

/** ids must be unique after `sanitizeIdent` since every id becomes a top-level `const` name in
 *  the generated barrel; two ids that sanitize to the same identifier would silently collide. */
function assertNoIdentCollisions(ids: string[]): void {
    const byIdent = new Map<string, string[]>();
    for (const id of ids) {
        const ident = sanitizeIdent(id);
        const bucket = byIdent.get(ident);
        if (bucket) bucket.push(id);
        else byIdent.set(ident, [id]);
    }
    const collisions = [...byIdent.entries()].filter(([, raw]) => raw.length > 1);
    if (collisions.length === 0) return;
    const detail = collisions.map(([ident, raw]) => `  '${ident}' ← ${raw.map((s) => `'${s}'`).join(', ')}`).join('\n');
    throw new Error(`[bongle] sound ids collide after identifier sanitization (ids must be globally unique):\n${detail}`);
}

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
function sanitizeIdent(id: string): string {
    if (IDENT_RE.test(id)) return id;
    let s = id.replace(/[^A-Za-z0-9_$]/g, '_');
    if (/^[0-9]/.test(s)) s = `_${s}`;
    return s;
}

function fmtNum(n: number): string {
    if (Object.is(n, -0)) return '0';
    return Number.isInteger(n) ? n.toFixed(1) : String(n);
}
