// per-scene codegen barrel.
//
// reads the captured `module.scenes` (declared via `scene('<id>')` in user
// code) and emits `src/generated/scenes.ts`. the barrel static-imports each
// scene's `.scene.json` and calls `registerScene` (imported from
// `bongle/internal`) at module-eval.
// each call stashes the payload into an engine-side map. `EngineClient.load`
// / `EngineServer.load` walk that map after `Project.load` and apply each
// payload via `populateScene`.
//
// edit mode additionally walks `content/scenes/blueprints/**` and registers
// every blueprint `.scene.json` found. blueprints are editor-authored, no
// user code calls `scene('blueprints/foo')`, so the walk is the only path
// that gets them into the registry where the icon renderer can find them.
// play mode keeps the strict "declared only" surface so prod bundles don't
// grow with editor-only artifacts.
//
// the module host resolves the JSON imports against the project filesystem;
// per-chunk binary payloads inside the json are gzip-base64 strings that
// stay inert until `loadVoxels` decodes them at runtime.

import type { ModuleVersion } from '../../internal';
import type { Filesystem } from '../filesystem';

const SCENES_DIR = 'content/scenes';
const SCENE_EXT = '.scene.json';
const BARREL_PATH = 'src/generated/scenes.ts';
// the barrel sits at src/generated/, two levels below the project root, so
// a project-root-relative scene path imports as ../../<path>.
const IMPORT_PREFIX = '../../';

const EMPTY_BARREL = `// auto-generated by asset pipeline — do not edit
export {};
`;

export type BuildScenesOptions = {
    /** bake invocation mode. `edit` additionally walks
     *  `content/scenes/blueprints/**` so editor-authored blueprints get a
     *  SceneHandle (used by the icon renderer + prefab placement). `play`
     *  registers only ids declared via `scene('id')`. */
    mode: 'edit' | 'play';
    /** the editor project filesystem (host-provided; see pipeline InitCtx). */
    fs: Filesystem;
};

export async function buildScenes(module: ModuleVersion, opts: BuildScenesOptions): Promise<void> {
    const { mode, fs } = opts;

    // union of declared ids + (edit mode) discovered blueprints. Set
    // preserves dedup; sort for stable barrel output. the walk is scoped
    // to `blueprints/` so an undeclared `content/scenes/foo.scene.json`
    // doesn't get auto-registered with a SceneHandle, the runtime only
    // sees scenes the user actually declared via `scene()`, plus blueprints.
    const ids = new Set<string>(module.scenes.keys());
    if (mode === 'edit') {
        const blueprintsDir = `${SCENES_DIR}/blueprints`;
        for (const entry of await fs.list(blueprintsDir, { recursive: true })) {
            if (entry.kind !== 'file' || !entry.path.endsWith(SCENE_EXT)) continue;
            // ids are scene-dir-relative ('blueprints/tree').
            ids.add(entry.path.slice(SCENES_DIR.length + 1, -SCENE_EXT.length));
        }
    }
    const sortedIds = Array.from(ids).sort();

    type Entry = { id: string; sceneRel: string };
    const entries: Entry[] = [];

    for (const id of sortedIds) {
        const scenePath = `${SCENES_DIR}/${id}${SCENE_EXT}`;
        if (!(await fs.exists(scenePath))) {
            // declaration exists but file doesn't, warn and skip. handle
            // stays empty; prefabs depending on it won't instantiate.
            console.warn(
                `[bongle] declared scene "${id}" not found — handle stays empty, prefabs depending on it won't instantiate`,
            );
            continue;
        }
        entries.push({ id, sceneRel: `${IMPORT_PREFIX}${scenePath}` });
    }

    if (entries.length === 0) {
        await fs.writeIfChanged(BARREL_PATH, EMPTY_BARREL);
        return;
    }

    const lines: string[] = [];
    lines.push(`// auto-generated by asset pipeline — do not edit`);
    lines.push(``);
    for (let i = 0; i < entries.length; i++) {
        lines.push(`import _scene_${i} from '${entries[i]!.sceneRel}';`);
    }
    lines.push(``);
    lines.push(`import { registerScene } from 'bongle/internal';`);
    lines.push(``);
    for (let i = 0; i < entries.length; i++) {
        const e = entries[i]!;
        lines.push(
            `registerScene(${JSON.stringify(e.id)}, { nodes: _scene_${i}.nodes, voxels: _scene_${i}.chunks ? { chunks: _scene_${i}.chunks } : null });`,
        );
    }
    lines.push(``);
    lines.push(`export {};`);
    lines.push(``);

    await fs.writeIfChanged(BARREL_PATH, lines.join('\n'));
}
