import type { Filesystem } from '../../../os/interface';
import type { ModuleVersion } from '../../internal';

const SCENES_DIR = 'content/scenes';
const SCENE_EXT = '.scene.json';
const BARREL_PATH = 'src/generated/scenes.ts';
// the barrel sits at src/generated/, two levels below the project root, so
// a project-root-relative scene path imports as ../../<path>.
const IMPORT_PREFIX = '../../';

const EMPTY_BARREL = `// auto-generated by asset pipeline — do not edit
export {};
`;

export type BuildScenesOptions = {
    /** `edit` additionally walks `content/scenes/blueprints/**` for a SceneHandle; `play`
     *  registers only ids declared via `scene('id')`. */
    mode: 'edit' | 'play';
    /** standalone: no server to serve scenes, so bakes every authored `content/scenes/*.json`,
     *  not just `scene()`-declared ids, or an editor-authored scene with no `scene('id')` call
     *  would be absent client-side and a local room couldn't boot it. */
    standalone: boolean;
    /** the editor project filesystem (host-provided; see pipeline InitCtx). */
    fs: Filesystem;
};

export async function buildScenes(module: ModuleVersion, opts: BuildScenesOptions): Promise<void> {
    const { mode, standalone, fs } = opts;

    // union of declared ids + discovered files; sort for stable barrel output.
    const ids = new Set<string>(module.scenes.keys());
    if (standalone) {
        // walks all of content/scenes/ (blueprints included, they live here too).
        for (const entry of await fs.list(SCENES_DIR)) {
            if (entry.kind !== 'file' || !entry.path.endsWith(SCENE_EXT)) continue;
            ids.add(entry.path.slice(SCENES_DIR.length + 1, -SCENE_EXT.length));
        }
    } else if (mode === 'edit') {
        // an undeclared non-blueprint scene stays server-only, matching the strict play surface.
        const blueprintsDir = `${SCENES_DIR}/blueprints`;
        for (const entry of await fs.list(blueprintsDir)) {
            if (entry.kind !== 'file' || !entry.path.endsWith(SCENE_EXT)) continue;
            // ids are scene-dir-relative ('blueprints/tree').
            ids.add(entry.path.slice(SCENES_DIR.length + 1, -SCENE_EXT.length));
        }
    }
    const sortedIds = Array.from(ids).sort();

    type Entry = { id: string; sceneRel: string };
    const entries: Entry[] = [];

    for (const id of sortedIds) {
        const scenePath = `${SCENES_DIR}/${id}${SCENE_EXT}`;
        if (!(await fs.exists(scenePath))) {
            console.warn(
                `[bongle] declared scene "${id}" not found — handle stays empty, prefabs depending on it won't instantiate`,
            );
            continue;
        }
        entries.push({ id, sceneRel: `${IMPORT_PREFIX}${scenePath}` });
    }

    if (entries.length === 0) {
        await fs.writeIfChanged(BARREL_PATH, EMPTY_BARREL);
        return;
    }

    const lines: string[] = [];
    lines.push(`// auto-generated by asset pipeline — do not edit`);
    lines.push(``);
    for (let i = 0; i < entries.length; i++) {
        lines.push(`import _scene_${i} from '${entries[i]!.sceneRel}';`);
    }
    lines.push(``);
    lines.push(`import { registerScene } from 'bongle/internal';`);
    lines.push(``);
    for (let i = 0; i < entries.length; i++) {
        const e = entries[i]!;
        lines.push(
            `registerScene(${JSON.stringify(e.id)}, { nodes: _scene_${i}.nodes, voxels: _scene_${i}.chunks ? { chunks: _scene_${i}.chunks } : null });`,
        );
    }
    lines.push(``);
    lines.push(`export {};`);
    lines.push(``);

    await fs.writeIfChanged(BARREL_PATH, lines.join('\n'));
}
