// GENERATED by scripts/stamp-build-info.mjs — do not edit by hand.
//
// The engine's build identity, stamped from git at `pnpm run build` time. Used
// for provenance: which exact engine a bundle was built with / a save was
// authored against. Compatibility gating keys on INTERFACE_VERSION, not this.

/** The engine package version (lib/package.json), the git short SHA, and the
 *  commit date (YYYYMMDD) the dist was built from. */
export const BONGLE_BUILD = {
    version: '0.0.0-alpha.1',
    sha: 'acdf20a4',
    date: '20260804',
} as const;

/** Composed engine identity: the package semver with git build metadata appended
 *  (semver `+build` syntax), e.g. `0.0.0-alpha.1+gacdf20a4.20260804`. Forward-
 *  compatible with real semver — the core becomes meaningful when the package is
 *  versioned + published; the `+g...` metadata stays. */
export const BONGLE_VERSION = `${BONGLE_BUILD.version}+g${BONGLE_BUILD.sha}.${BONGLE_BUILD.date}`;
