export * from './api/animation';
export * from './api/asset';
export * from './api/audio';
export * from './api/avatars';
export * from './api/blocks';
export * as chat from './api/chat';
export { client } from './api/client';
export { clientToUser } from './api/clients';
export * from './api/config';
export * from './api/crosshair';
export * as debug from './api/debug';
export * from './api/environment';
export * from './api/input';
export * from './api/lighting';
export * from './api/mobile';
export * from './api/models';
export * from './api/nav';
export * from './api/pack';
export * from './api/particles';
export * from './api/physics';
export { platform } from './api/platform';
export * from './api/pointer-lock';
export * from './api/prefabs';
export * from './api/prop';
export * from './api/render';
export * as rooms from './api/rooms';
export * from './api/rpc';
export * from './api/scene-tree';
export * from './api/scenes';
export * from './api/scripts';
export * from './api/sounds';
export * from './api/sprites';
export { projectStorage, userStorage } from './api/storage';
export * from './api/subject';
export * from './api/textures';
export * from './api/touch-controls';
export * from './api/traits';
export * from './api/transforms';
export * from './api/use';
export { BONGLE_BUILD, BONGLE_VERSION } from './build-info';
export * from './builtins/aabb-body';
export * from './builtins/animator';
export * from './builtins/audio-listener';
export * from './builtins/camera';
export * from './builtins/canvas';
export * from './builtins/character';
export * from './builtins/character-controller';
export * from './builtins/contacts';
export * from './builtins/extruded-sprite';
export * from './builtins/fly-controller';
export * from './builtins/html';
export * from './builtins/marker';
export * from './builtins/mesh';
export * from './builtins/orbit-controller';
export * from './builtins/player';
export * from './builtins/player-controller';
export * from './builtins/rigid-body';
export * from './builtins/shadow-caster';
export * from './builtins/sprite';
export * from './builtins/text';
// only the trait: the transform module's other 44 exports are engine internals
// (dirty bits, compose/sweep primitives, invalidation hooks). The user-facing
// setters and getters come through `./api/transforms`.
export { TransformTrait } from './builtins/transform';
export * from './builtins/voxel-mesh';
export * from './builtins/world';
// debug widget surface types (client/debug), for games annotating panels/controls built via
// `debug.panel(ctx, …)` or `ctx.client.debug.dashboard`.
export type { AddOptions, Dashboard, Handle, LogEntry, Panel, PanelOptions } from './client/debug';
export { UILayer } from './client/ui/util/ui-layers';
export type { Avatar } from './core/avatar/avatar';
export { env } from './env';
